---
title: "en-net"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    social: [ "twitter", "linkedin" ]
    source_code: https://github.com/katilingban/ennetdashboard
    theme: lumen
---

<!--- Custom CSS: Change colour of tabset top border --->
<style>
.nav-tabs-custom > .nav-tabs > li.active { border-top-color: #43925B }
</style>
<!--- end --->


```{r setup, include = FALSE}
## Libraries -------------------------------------------------------------------
library(flexdashboard)
library(shiny)
library(ggplot2)
library(magrittr)
library(plotly)
library(lubridate)
library(remotes)
library(dplyr)
library(tidyr)
library(ennet)

## Create Mapbox base layer objects for leaflet mapping ------------------------
mapbox.satellite <- "https://api.mapbox.com/styles/v1/mapbox/satellite-streets-v10/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1IjoiZXJuZXN0Z3VldmFycmEiLCJhIjoiejRRLXlZdyJ9.sqS1zi0rDH5CIzvcn9SXSg"
mapbox.street    <- "https://api.mapbox.com/styles/v1/mapbox/streets-v10/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1IjoiZXJuZXN0Z3VldmFycmEiLCJhIjoiejRRLXlZdyJ9.sqS1zi0rDH5CIzvcn9SXSg"
mapbox.dark      <- "https://api.mapbox.com/styles/v1/mapbox/dark-v9/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1IjoiZXJuZXN0Z3VldmFycmEiLCJhIjoiejRRLXlZdyJ9.sqS1zi0rDH5CIzvcn9SXSg"
mapbox.light     <- "https://api.mapbox.com/styles/v1/mapbox/light-v9/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1IjoiZXJuZXN0Z3VldmFycmEiLCJhIjoiejRRLXlZdyJ9.sqS1zi0rDH5CIzvcn9SXSg"
mapbox.moonlight <- "https://api.mapbox.com/styles/v1/ernestguevarra/cj3nban30001z2rpahc10c9ef/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1IjoiZXJuZXN0Z3VldmFycmEiLCJhIjoiejRRLXlZdyJ9.sqS1zi0rDH5CIzvcn9SXSg"
mapbox.northstar <- "https://api.mapbox.com/styles/v1/ernestguevarra/cj4ke832y4sng2spe2ds4fs55/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1IjoiZXJuZXN0Z3VldmFycmEiLCJhIjoiejRRLXlZdyJ9.sqS1zi0rDH5CIzvcn9SXSg"
mapbox.standard  <- "https://api.mapbox.com/styles/v1/ernestguevarra/cj5di36jn0gxg2rphjn3yetpt/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1IjoiZXJuZXN0Z3VldmFycmEiLCJhIjoiejRRLXlZdyJ9.sqS1zi0rDH5CIzvcn9SXSg"
mapbox.decimal   <- "https://api.mapbox.com/styles/v1/ernestguevarra/cj5ms1akt3pbi2smtcewsex9m/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1IjoiZXJuZXN0Z3VldmFycmEiLCJhIjoiejRRLXlZdyJ9.sqS1zi0rDH5CIzvcn9SXSg"
mapbox.terminal  <- "https://api.mapbox.com/styles/v1/ernestguevarra/cj6g0tzbd30kc2sph2wyh666m/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1IjoiZXJuZXN0Z3VldmFycmEiLCJhIjoiejRRLXlZdyJ9.sqS1zi0rDH5CIzvcn9SXSg"
mapbox.leshine  <- "https://api.mapbox.com/styles/v1/ernestguevarra/cjdlr8pvl0xiv2sqvq1evk1pl/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1IjoiZXJuZXN0Z3VldmFycmEiLCJhIjoiejRRLXlZdyJ9.sqS1zi0rDH5CIzvcn9SXSg"

## Load UNICEF palette ---------------------------------------------------------
ennet_green      <- "#43925B"
ennet_darkgreen  <- "#008A35"

unicef_blue      <- "#1CABE2"
unicef_darkgreen <- "#00833D"
unicef_green     <- "#80BD41"
unicef_yellow    <- "#FFC20E"
unicef_orange    <- "#F26A21"
unicef_red       <- "#E2231A"
unicef_darkred   <- "#961A49" 
unicef_purple    <- "#6A1E74"
unicef_warmgrey  <- "#D8D1C9"
unicef_coolgrey  <- "#777779"
unicef_black     <- "#2D2926"
unicef_darkblue  <- "#374EA2"

## UNICEF ggplot theme settings ------------------------------------------------
unicef_theme <- theme_bw() +
  theme(text = element_text(family = "Helvetica"),
        plot.title = element_text(size = 16, colour = ennet_darkgreen),
        plot.subtitle = element_text(size = 14, colour = ennet_green),
        panel.border = element_rect(colour = ennet_darkgreen,
                                    size = 0.5),
        panel.grid.major = element_line(linetype = 0),
        panel.grid.minor = element_line(linetype = 0),
        strip.background = element_rect(colour = ennet_darkgreen,
                                        fill = ennet_darkgreen),
        strip.text = element_text(face = "bold", 
                                  colour = "white", 
                                  size = 10, 
                                  vjust = 1),
        legend.background = element_rect(colour = NA, fill = NA),
        legend.key = element_rect(linetype = 0),
        legend.key.size = unit(x = 8, units = "points"),
        legend.spacing = unit(x = 4, units = "points"),
        legend.text = element_text(size =  8),
        legend.position = "top",
        axis.line.x = element_line(colour = ennet_darkgreen, size = 0.5),
        axis.text.x = element_text(size = 10, colour = ennet_darkgreen),
        axis.title.x = element_text(size = 12, colour = ennet_green),
        axis.text.y = element_text(size = 10, colour = ennet_darkgreen),
        axis.title.y = element_text(size = 12, colour = ennet_green),
        axis.ticks = element_line(colour = ennet_darkgreen, size = 0.25))

## Get data --------------------------------------------------------------------

## Get discussions dataset
discussions <- get_db_discussions()

## Get themes data
themes <- get_themes()$themes

## Get topics by themes data
topics <- get_themes_topics()

## Process dailies topics data
daily_interactions <- get_db_topics(id = "daily") %>%
  dplyr::mutate(`New Replies` = ifelse(`New Replies` < 0, 0, `New Replies`),
                `New Views` = ifelse(`New Views` < 0, 0, `New Views`))

## Process weeklies topics data
weekly_interactions <- get_db_topics(id = "weekly") %>%
  dplyr::mutate(`New Replies` = ifelse(`New Replies` < 0, 0, `New Replies`),
                `New Views` = ifelse(`New Views` < 0, 0, `New Views`))

## Process monthlies topics data
monthly_interactions <- get_db_topics(id = "monthly")

## Process yearlies topics data
yearly_interactions <- get_db_topics(id = "yearly")
```

Overview
================================================================================

Inputs {.sidebar}
--------------------------------------------------------------------------------

```{r filters1}
h4("Filters")

selectInput(inputId = "themes_options",
            label = "Themes",
            choices = themes,
            selected = themes[1:3],
            multiple = TRUE)

selectInput(inputId = "year_start",
            label = "From",
            selected = min(unique(lubridate::year(topics$Posted))),
            choices = rev(unique(lubridate::year(topics$Posted))))

selectInput(inputId = "year_end",
            label = "To",
            selected = max(unique(lubridate::year(topics$Posted))),
            choices = rev(unique(lubridate::year(topics$Posted))))

selectInput(inputId = "frequency_options",
            label = "Frequency",
            selected = "Daily",
            choices = c("Daily", "Weekly", "Monthly", "Yearly"))

selectInput(inputId = "scale_options",
            label = "Scale options",
            selected = "fixed",
            choices = c("fixed", "free", "free_x", "free_y"))
```

Row {.tabset .tabset-fade}
--------------------------------------------------------------------------------

### Posts

```{r posts_output}
output$posts <- renderPlotly({
  req(input$themes_options)
  
  ## Get time period
  time_period <- input$year_start:input$year_end
  
  ## Tally dailies and then filter to specified themes and time period
  x <- topics %>%
    filter(Theme %in% input$themes_options,
           lubridate::year(Posted) %in% time_period)
  
  ## Daily
  if (input$frequency_options == "Daily") {
    y <- x %>%
      count_topics_theme_time(by_time = "day") %>%
      ggplot(mapping = aes(x = day, y = n)) +
      #geom_col(fill = ennet_green, colour = ennet_green, alpha = 0.5) +
      geom_area(fill = ennet_green, colour = ennet_green, alpha = 0.5) +
      scale_x_date(name = "", 
                   #date_breaks = "1 month",
                   date_labels = "%b %Y") %>%
      labs(title = "Number of questions posted per day by theme",
           x = "",
           y = "No. of questions posted") +
      facet_wrap(. ~ Theme, ncol = 1, scales = input$scale_options) +
      unicef_theme
  }
  
  ## Weekly
  if (input$frequency_options == "Weekly") {
    y <- x %>%
      count_topics_theme_time(by_time = "week") %>%
      ggplot(mapping = aes(x = week, y = n)) +
      #geom_col(fill = ennet_green, 
      #         colour = ennet_green, 
      #         alpha = 0.5) +
      geom_area(fill = ennet_green, colour = ennet_green, alpha = 0.5) +
      scale_x_date(name = "",
                   #date_breaks = "12 weeks", 
                   date_labels = "Week %V-%Y") +
      labs(title = "Number of questions posted per week by theme",
           x = "",
           y = "No. of questions posted") +
      facet_wrap(. ~ Theme, ncol = 1, scales = input$scale_options) +
      unicef_theme #+
      #theme(axis.text.x = element_text(size = 8, angle = 90),
      #      axis.text.y = element_text(size = 8))
  }
  
  if (input$frequency_options == "Monthly") {
    y <- x %>%
      count_topics_theme_time(by_time = "month") %>%
      ggplot(mapping = aes(x = month, y = n)) +
      #geom_col(fill = ennet_green, colour = ennet_green, alpha = 0.5) +
      geom_area(fill = ennet_green, colour = ennet_green, alpha = 0.5) +
      scale_x_date(name = "", 
                   #date_breaks = "3 months", 
                   date_labels = "%b %Y") +
      labs(title = "Number of questions posted per month by theme",
           x = "",
           y = "No. of questions posted") +
      facet_wrap(. ~ Theme, ncol = 1, scales = input$scale_options) +
      unicef_theme #+
      #theme(axis.text.x = element_text(size = 8, angle = 90),
      #      axis.text.y = element_text(size = 8))
  }
  
  if (input$frequency_options == "Yearly") {
    y <- x %>%
      count_topics_theme_time(by_time = "year") %>%
      ggplot(mapping = aes(x = year, y = n)) +
      #geom_col(fill = ennet_green, colour = ennet_green, alpha = 0.5) +
      geom_area(fill = ennet_green, colour = ennet_green, alpha = 0.5) +
      scale_x_date(name = "", date_labels = "%Y") +
      labs(title = "Number of questions posted per year by theme",
           x = "",
           y = "No. of questions posted") +
      facet_wrap(. ~ Theme, ncol = 1, scales = input$scale_options) +
      unicef_theme
  }
  
  ggplotly(p = y)
})

plotlyOutput(outputId = "posts")
```

### Views

```{r views_outputs}
output$views <- renderPlotly({
  req(input$themes_options)
  
  ## Get time period
  time_period <- input$year_start:input$year_end
  
  if (input$frequency_options == "Daily") {
    z <- daily_interactions %>%
      filter(Theme %in% input$themes_options,
             lubridate::year(`Extraction Date`) %in% time_period) %>%
      group_by(Theme, `Extraction Date`) %>%
      mutate(`Total views per post per day` = Views / nPosts,
             `New views per post per day` = `New Views` / nPosts) %>%
      ggplot(mapping = aes(x = `Extraction Date`, 
                           y = `New views per post per day`)) +
      #geom_col(fill = ennet_green, colour = ennet_green, alpha = 0.5) +
      geom_area(fill = ennet_green, colour = ennet_green, alpha = 0.5) +
      scale_x_date(name = "", 
                   date_breaks = "1 month",
                   date_labels = "%b %Y") %>%
      labs(title = "New views per post per day by theme",
           x = "",
           y = "No. of new views") +
      facet_wrap(. ~ Theme, ncol = 1, scales = input$scale_options) +
      unicef_theme
  }
  
  if (input$frequency_options == "Weekly") {
    z <- weekly_interactions %>%
      filter(Theme %in% input$themes_options,
             lubridate::year(`Extraction Week`) %in% time_period) %>%
      group_by(Theme, `Extraction Week`) %>%
      mutate(`Total views per post per week` = Views / nPosts,
             `New views per post per week` = `New Views` / nPosts) %>%
      ggplot(mapping = aes(x = `Extraction Week`, 
                           y = `New views per post per week`)) +
      #geom_col(fill = ennet_green, colour = ennet_green, alpha = 0.5) +
      geom_area(fill = ennet_green, colour = ennet_green, alpha = 0.5) +
      scale_x_date(name = "", 
                   date_breaks = "1 month",
                   date_labels = "Week %V-%Y") %>%
      labs(title = "New views per post per week by theme",
           x = "",
           y = "No. of new views") +
      facet_wrap(. ~ Theme, ncol = 1, scales = input$scale_options) +
      unicef_theme
  }
  
  if (input$frequency_options == "Monthly") {
    z <- monthly_interactions %>%
      filter(Theme %in% input$themes_options,
             lubridate::year(`Extraction Month`) %in% time_period) %>%
      group_by(Theme, `Extraction Month`) %>%
      mutate(`Total views per post per month` = Views / nPosts,
             `New views per post per month` = `New Views` / nPosts) %>%
      ggplot(mapping = aes(x = `Extraction Month`, 
                           y = `New views per post per month`)) +
      #geom_col(fill = ennet_green, colour = ennet_green, alpha = 0.5) +
      geom_area(fill = ennet_green, colour = ennet_green, alpha = 0.5) +
      scale_x_date(name = "", 
                   date_breaks = "1 month",
                   date_labels = "%b-%Y") %>%
      labs(title = "New views per post per month by theme",
           x = "",
           y = "No. of new views") +
      facet_wrap(. ~ Theme, ncol = 1, scales = input$scale_options) +
      unicef_theme
  }
  
  if (input$frequency_options == "Yearly") {
    z <- yearly_interactions %>%
      filter(Theme %in% input$themes_options,
             lubridate::year(`Extraction Year`) %in% time_period) %>%
      group_by(Theme, `Extraction Year`) %>%
      mutate(`Total views per post per year` = Views / nPosts,
             `New views per post per year` = `New Views` / nPosts) %>%
      ggplot(mapping = aes(x = `Extraction Year`, 
                           y = `New views per post per year`)) +
      #geom_col(fill = ennet_green, colour = ennet_green, alpha = 0.5) +
      geom_area(fill = ennet_green, colour = ennet_green, alpha = 0.5) +
      scale_x_date(name = "", 
                   date_breaks = "1 month",
                   date_labels = "%Y") %>%
      labs(title = "New views per post per year by theme",
           x = "",
           y = "No. of new views") +
      facet_wrap(. ~ Theme, ncol = 1, scales = input$scale_options) +
      unicef_theme
  }
  
  ggplotly(p = z)
})

plotlyOutput(outputId = "views")
```

### Replies

```{r replies_outputs}
output$replies <- renderPlotly({
  req(input$themes_options)
  
  ## Get time period
  time_period <- input$year_start:input$year_end
  
  if (input$frequency_options == "Daily") {
    z <- daily_interactions %>%
      filter(Theme %in% input$themes_options,
             lubridate::year(`Extraction Date`) %in% time_period) %>%
      group_by(Theme, `Extraction Date`) %>%
      mutate(`Total replies per 10000 views per day` = Replies / (Views / 10000),
             `New replies per 10000 views per day` = `New Replies` / (Views / 10000)) %>%
      ggplot(mapping = aes(x = `Extraction Date`, 
                           y = `New replies per 10000 views per day`)) +
      #geom_col(fill = ennet_green, colour = ennet_green, alpha = 0.5) +
      geom_area(fill = ennet_green, colour = ennet_green, alpha = 0.5) +
      scale_x_date(name = "", 
                   #date_breaks = "1 month",
                   date_labels = "%b %Y") %>%
      labs(title = "New replies per 10000 views per day by theme",
           x = "",
           y = "No. of new replies") +
      facet_wrap(. ~ Theme, ncol = 1, scales = input$scale_options) +
      unicef_theme
  }
  
  if (input$frequency_options == "Weekly") {
    z <- weekly_interactions %>%
      filter(Theme %in% input$themes_options,
             lubridate::year(`Extraction Week`) %in% time_period) %>%
      group_by(Theme, `Extraction Week`) %>%
      mutate(`Total replies per 10000 views per week` = Replies / (Views / 10000),
             `New replies per 10000 views per week` = `New Replies` / (Views / 10000)) %>%
      ggplot(mapping = aes(x = `Extraction Week`, 
                           y = `New replies per 10000 views per week`)) +
      #geom_col(fill = ennet_green, colour = ennet_green, alpha = 0.5) +
      geom_area(fill = ennet_green, colour = ennet_green, alpha = 0.5) +
      scale_x_date(name = "", 
                   #date_breaks = "1 month",
                   date_labels = "Week %V-%Y") %>%
      labs(title = "New replies per 10000 views per week by theme",
           x = "",
           y = "No. of new replies") +
      facet_wrap(. ~ Theme, ncol = 1, scales = input$scale_options) +
      unicef_theme
  }
  
  if (input$frequency_options == "Monthly") {
    z <- monthly_interactions %>%
      filter(Theme %in% input$themes_options,
             lubridate::year(`Extraction Month`) %in% time_period) %>%
      group_by(Theme, `Extraction Month`) %>%
      mutate(`Total replies per 10000 views per month` = Replies / (Views / 10000),
             `New replies per 10000 views per month` = `New Replies` / (Views / 10000)) %>%
      ggplot(mapping = aes(x = `Extraction Month`, 
                           y = `New replies per 10000 views per month`)) +
      #geom_col(fill = ennet_green, colour = ennet_green, alpha = 0.5) +
      geom_area(fill = ennet_green, colour = ennet_green, alpha = 0.5) +
      scale_x_date(name = "", 
                   #date_breaks = "1 month",
                   date_labels = "%b-%Y") %>%
      labs(title = "New replies per 10000 views per month by theme",
           x = "",
           y = "No. of new replies") +
      facet_wrap(. ~ Theme, ncol = 1, scales = input$scale_options) +
      unicef_theme
  }
  
  if (input$frequency_options == "Yearly") {
    z <- yearly_interactions %>%
      filter(Theme %in% input$themes_options,
             lubridate::year(`Extraction Year`) %in% time_period) %>%
      group_by(Theme, `Extraction Year`) %>%
      mutate(`Total replies per 10000 views per year` = Replies / (Views / 10000),
             `New replies per 10000 views per year` = `New Replies` / (Views / 10000)) %>%
      ggplot(mapping = aes(x = `Extraction Year`, 
                           y = `New replies per 10000 views per year`)) +
      #geom_col(fill = ennet_green, colour = ennet_green, alpha = 0.5) +
      geom_area(fill = ennet_green, colour = ennet_green, alpha = 0.5) +
      scale_x_date(name = "", 
                   #date_breaks = "1 month",
                   date_labels = "%Y") %>%
      labs(title = "New replies per 10000 views per year by theme",
           x = "",
           y = "No. of new replies") +
      facet_wrap(. ~ Theme, ncol = 1, scales = input$scale_options) +
      unicef_theme
  }
  
  ggplotly(p = z)
})

plotlyOutput(outputId = "replies")
```

Top of the Charts
================================================================================

Inputs {.sidebar}
--------------------------------------------------------------------------------

```{r filters2}
h4("Filters")

#selectInput(inputId = "themes_choices",
#            label = "Themes",
#            choices = themes,
#            selected = themes[1])

#selectInput(inputId = "year_first",
#            label = "From",
#            selected = min(unique(lubridate::year(topics$Posted))),
#            choices = rev(unique(lubridate::year(topics$Posted))))

#selectInput(inputId = "year_last",
#            label = "To",
#            selected = max(unique(lubridate::year(topics$Posted))),
#            choices = rev(unique(lubridate::year(topics$Posted))))

selectInput(inputId = "frequency_choices",
            label = "Frequency",
            selected = "Weekly",
            choices = c("Weekly", "Monthly", "Yearly"))

#selectInput(inputId = "scale_choices",
#            label = "Scale options",
#            selected = "fixed",
#            choices = c("fixed", "free", "free_x", "free_y"))
```

Row {.tabset .tabset-fade}
--------------------------------------------------------------------------------

### Posts

```{r posts_charts}
output$posts_charts <- renderPlotly({
  
  if (input$frequency_choices == "Weekly") {
    frequency_period <- seq(from = Sys.Date() - 7, 
                            to = Sys.Date(), 
                            by = 1)
  }
  
  if (input$frequency_choices == "Monthly") {
    frequency_period <- seq(from = Sys.Date() - 30, 
                            to = Sys.Date(), 
                            by = 1)
  }
  
  if (input$frequency_choices == "Yearly") {
    frequency_period <- seq(from = Sys.Date() - 365, 
                            to = Sys.Date(), 
                            by = 1)
  }
  
  x <- topics %>%
    filter(Posted %in% frequency_period) %>%
    count_topics_theme(.sort = TRUE) %>%
    mutate(Theme = reorder(Theme, -n)) %>%
    ggplot(mapping = aes(x = Theme, y = n)) +
    geom_col(fill = ennet_green, colour = ennet_green, alpha = 0.5) +
    labs(title = paste("Period from ", min(frequency_period), " to ", 
                       max(frequency_period), sep = ""),
         x = "", y = "Number of posts") +
    coord_flip() +
    unicef_theme
           
  ggplotly(p = x)
})

plotlyOutput(outputId = "posts_charts")
```

### Views

```{r views_charts}
output$views_charts <- renderPlotly({

  x <- topics %>%
    group_by(Theme, Posted) %>%
    summarise(`Total views` = sum(Views)) %>%
    ungroup() %>%
    rename(day = Posted)
  
  y <- topics %>%
    count_topics_theme_time(by_time = "day") %>%
    left_join(x, by = c("Theme", "day"))
    
  if (input$frequency_choices == "Weekly") {
    frequency_period <- seq(from = Sys.Date() - 7, 
                            to = Sys.Date(), 
                            by = 1)
  }
  
  if (input$frequency_choices == "Monthly") {
    frequency_period <- seq(from = Sys.Date() - 30, 
                            to = Sys.Date(), 
                            by = 1)
  }
  
  if (input$frequency_choices == "Yearly") {
    frequency_period <- seq(from = Sys.Date() - 365, 
                            to = Sys.Date(), 
                            by = 1)
  }
  
  z <- y %>%
    filter(day %in% frequency_period) %>%
    group_by(Theme) %>%
    summarise(`Total views` = sum(`Total views`),
              `Total posts` = sum(n),
              `Total views per post` = `Total views` / `Total posts`) %>%
    mutate(Theme = reorder(Theme, -`Total views per post`)) %>%
    ggplot(mapping = aes(x = Theme,
                         y = `Total views per post`)) +
    geom_col(fill = ennet_green, colour = ennet_green, alpha = 0.5) +
    labs(title = paste("Period from ", min(frequency_period), 
                       " to ", max(frequency_period), sep = ""),
         x = "", y = "Total views per post") +
    coord_flip() +
    unicef_theme
  
  ggplotly(p = z)
})
  
plotlyOutput(outputId = "views_charts")
```

### Replies

```{r replies_charts}
output$replies_charts <- renderPlotly({

  x <- topics %>%
    group_by(Theme, Posted) %>%
    summarise(`Total views` = sum(Views),
              `Total replies` = sum(Replies)) %>%
    ungroup() %>%
    rename(day = Posted)
  
  y <- topics %>%
    count_topics_theme_time(by_time = "day") %>%
    left_join(x, by = c("Theme", "day"))
    
  if (input$frequency_choices == "Weekly") {
    frequency_period <- seq(from = Sys.Date() - 7, 
                            to = Sys.Date(), 
                            by = 1)
  }
  
  if (input$frequency_choices == "Monthly") {
    frequency_period <- seq(from = Sys.Date() - 30, 
                            to = Sys.Date(), 
                            by = 1)
  }
  
  if (input$frequency_choices == "Yearly") {
    frequency_period <- seq(from = Sys.Date() - 365, 
                            to = Sys.Date(), 
                            by = 1)
  }
  
  z <- y %>%
    filter(day %in% frequency_period) %>%
    group_by(Theme) %>%
    summarise(`Total replies` = sum(`Total replies`),
              `Total views` = sum(`Total views`),
              `Total replies per view` = `Total replies` / `Total views`) %>%
    mutate(Theme = reorder(Theme, -`Total replies per view`)) %>%
    ggplot(mapping = aes(x = Theme,
                         y = `Total replies per view`)) +
    geom_col(fill = ennet_green, colour = ennet_green, alpha = 0.5) +
    labs(title = paste("Period from ", min(frequency_period), 
                       " to ", max(frequency_period), sep = ""),
         x = "", y = "Total replies per view") +
    coord_flip() +
    unicef_theme
  
  ggplotly(p = z)
})
  
plotlyOutput(outputId = "replies_charts")
```