name: shinyapps

on:
  push:
    branches:
      - main
      - master
      
jobs:
  shinyapps:
    runs-on: macOS-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup R
        uses: r-lib/actions/setup-r@v1
        
      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@v1
        
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-shinydoc
          restore-keys: |
            ${{ runner.os }}-
        
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          install.packages(c("shiny", "flexdashboard", "tidyr", "magrittr",
                             "ggplot2", "plotly", "tidyr",
                             "plotly", "lubridate", "leaflet", "RColorBrewer", 
                             "rsconnect", "remotes"))
          remotes::install_github("katilingban/ennet")
          remotes::install_github("dgrtwo/drlib")
        shell: Rscript {0}
        
      - name: Configure shinyapps.io account
        env:
          SHINY_TOKEN: ${{ secrets.SHINY_TOKEN }}
          SHINY_SECRET: ${{ secrets.SHINY_SECRET }}
        
        run: |
          rsconnect::setAccountInfo(name = "katilingban",
                                    token = Sys.getenv("SHINY_TOKEN"),
                                    secret = Sys.getenv("SHINY_SECRET"))
        shell: Rscript {0}
          
      - name: Deploy to shinyapps.io
        run: |
          rsconnect::deployDoc(doc = "ennetdashboard.Rmd", 
            forceUpdate = getOption("rsconnect.force.update.apps", TRUE))
        shell: Rscript {0}
        