name: deploy_shinyapps

on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches:
      - main
      - master
  workflow_dispatch:
    branches:
      - '*'
      
jobs:
  deploy_shinyapps:
    runs-on: ubuntu-latest
    container: rocker/tidyverse:4.1.2
    steps:
      - uses: actions/checkout@v2
      
      - name: Install system dependencies
        run: |
          apt-get update && apt-get install -y --no-install-recommends \
          git-crypt libxt6 libglpk-dev
      
      - name: Install packages from renv.lock (with cache)
        if: ${{ !env.ACT }}  
        uses: r-lib/actions/setup-renv@master
        with:
          cache-version: 2

      - name: Install packages from renv.lock (local, no cache)
        if: ${{ env.ACT }}  
        run: |
          renv::restore()
        shell: Rscript {0}
        
      - name: Configure shinyapps.io account
        env:
          SHINY_TOKEN: ${{ secrets.SHINY_TOKEN }}
          SHINY_SECRET: ${{ secrets.SHINY_SECRET }}
        
        run: |
          rsconnect::setAccountInfo(name = "katilingban",
                                    token = Sys.getenv("SHINY_TOKEN"),
                                    secret = Sys.getenv("SHINY_SECRET"))
        shell: Rscript {0}
          
      - name: Deploy to shinyapps.io
        run: |
          rsconnect::deployDoc(doc = "ennetdashboard.Rmd", 
            forceUpdate = getOption("rsconnect.force.update.apps", TRUE))
        shell: Rscript {0}
        